// examples/quarkus/quarkus-pingcrm-svelte/src/main/webui/src/lib/Pages/Auth/Login.svelte
<script>
  import { useForm } from '@inertiajs/svelte'

  let form = useForm({
    email: 'johndoe@example.com',
    password: 'secret',
    remember: true,
  })

  function submit(e) {
    e.preventDefault()
    form.post('/login')
  }
</script>

<div class="flex min-h-screen items-center justify-center bg-indigo-500 p-6">
  <div class="w-full max-w-md">
    <div class="text-center mb-6">
      <svg class="mx-auto h-16 w-16 text-white" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="30" cy="30" r="28" stroke="currentColor" stroke-width="3" fill="none"/>
        <text x="30" y="38" text-anchor="middle" fill="currentColor" font-size="24" font-weight="bold">P</text>
      </svg>
      <h1 class="mt-4 text-3xl font-bold text-white">Ping CRM</h1>
      <p class="mt-1 text-indigo-200">Welcome Back!</p>
    </div>

    <form onsubmit={submit} class="bg-white rounded-lg shadow-md p-8">
      <div class="mb-4">
        <label for="email" class="block text-sm font-medium text-gray-700 mb-1">Email</label>
        <input
          id="email"
          type="email"
          bind:value={form.email}
          class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
        />
        {#if form.errors.email}
          <p class="mt-1 text-sm text-red-500">{form.errors.email}</p>
        {/if}
      </div>

      <div class="mb-4">
        <label for="password" class="block text-sm font-medium text-gray-700 mb-1">Password</label>
        <input
          id="password"
          type="password"
          bind:value={form.password}
          class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
        />
        {#if form.errors.password}
          <p class="mt-1 text-sm text-red-500">{form.errors.password}</p>
        {/if}
      </div>

      <div class="mb-4">
        <label class="flex items-center">
          <input type="checkbox" bind:checked={form.remember} class="rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
          <span class="ml-2 text-sm text-gray-600">Remember me</span>
        </label>
      </div>

      <button
        type="submit"
        disabled={form.processing}
        class="w-full rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold hover:bg-indigo-700 disabled:opacity-50 transition"
      >
        {#if form.processing}
          Logging in...
        {:else}
          Login
        {/if}
      </button>
    </form>
  </div>
</div>

// examples/spring/spring-pingcrm-react/src/main/webui/resources/js/Pages/Auth/Login.tsx
import { Head, useForm } from '@inertiajs/react'
import type { FormEvent } from 'react'
import Logo from '@/Shared/Logo'
import TextInput from '@/Shared/TextInput'
import LoadingButton from '@/Shared/LoadingButton'
import { useSyncErrors } from '@/composables/useSyncErrors'

interface LoginForm {
  email: string
  password: string
  remember: boolean
}

export default function Login() {
  const form = useForm<LoginForm>({
    email: 'johndoe@example.com',
    password: 'secret',
    remember: false,
  })
  useSyncErrors(form)

  const login = (e: FormEvent) => {
    e.preventDefault()
    form.post('/login')
  }

  return (
    <div>
      <Head title="Login" />
      <div className="flex items-center justify-center p-6 min-h-screen bg-indigo-800">
        <div className="w-full max-w-md">
          <Logo className="block mx-auto w-full max-w-xs fill-white" height={50} />
          <form className="mt-8 bg-white rounded-lg shadow-xl overflow-hidden" onSubmit={login}>
            <div className="px-10 py-12">
              <h1 className="text-center text-3xl font-bold">Welcome Back!</h1>
              <div className="mt-6 mx-auto w-24 border-b-2" />
              <TextInput
                value={form.data.email}
                onChange={(email) => form.setData('email', email)}
                error={form.errors.email}
                className="mt-10"
                label="Email"
                type="email"
                autoFocus
                autoCapitalize="off"
              />
              <TextInput
                value={form.data.password}
                onChange={(password) => form.setData('password', password)}
                error={form.errors.password}
                className="mt-6"
                label="Password"
                type="password"
              />
              <label className="flex items-center mt-6 select-none" htmlFor="remember">
                <input
                  id="remember"
                  className="mr-1"
                  type="checkbox"
                  checked={form.data.remember}
                  onChange={(e) => form.setData('remember', e.target.checked)}
                />
                <span className="text-sm">Remember Me</span>
              </label>
            </div>
            <div className="flex px-10 py-4 bg-gray-100 border-t border-gray-100">
              <LoadingButton loading={form.processing} className="btn-indigo ml-auto" type="submit">
                Login
              </LoadingButton>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}
