// examples/quarkus/quarkus-pingcrm-svelte/src/main/webui/src/lib/Pages/Probe/Index.svelte
<script>
  import { router, useForm, usePage } from '@inertiajs/svelte'

  let page = usePage()

  let form = useForm({ name: '', email: '' })
  let secondary = useForm({ title: '', body: '' })
  let upload = useForm({ photo: null })

  let greeting = $derived(page.props?.greeting ?? '')
  let notice = $derived(page.props?.notice ?? null)
  let slow = $derived(page.props?.slow ?? null)
  let entries = $derived(page.props?.entries ?? [])
  let success = $derived(page.props?.success ?? null)
  let bagErrors = $derived(page.props?.errors?.probeSecondary ?? null)

  // Probe pages are served under a variant base (/e2e-probe on Spring/JAX-RS,
  // /e2e-probe-rx on Reactive Routes): derive it from the current URL so every
  // form post and visit targets the same transport (E2E_PROBE_BASE). Called
  // from event handlers only, so server-side rendering never touches window.
  function probeBase() {
    return window.location.pathname.replace(/\/target\/?$/, '').replace(/\/+$/, '')
  }

  function submitPrimary(e) {
    e.preventDefault()
    form.post(probeBase() + '/validate')
  }

  function submitSecondary(e) {
    e.preventDefault()
    secondary.post(probeBase() + '/validate-secondary', {
      headers: { 'X-Inertia-Error-Bag': 'probeSecondary' },
    })
  }

  function submitUpload(e) {
    e.preventDefault()
    upload.post(probeBase() + '/upload')
  }

  function loadSlow() {
    router.reload({ only: ['slow'] })
  }

  function suppressNotice() {
    router.reload({ headers: { 'X-Inertia-Except-Once-Props': 'notice' } })
  }

  function fetchNextEntry() {
    router.reload({ only: ['entries'] })
  }

  function visitTarget() {
    router.visit(probeBase() + '/target?delay=2', {
      component: 'Probe/Target',
      pageProps: (current, shared) => ({
        ...shared,
        greeting: `Navigating from probe (was: "${current.greeting}")`,
      }),
    })
  }

  function redirectBack() {
    router.post(probeBase() + '/redirect-back')
  }

  function onPhoto(e) {
    upload.photo = e.target.files?.[0] ?? null
  }
</script>

<div class="mx-auto max-w-3xl p-8">
  <h1 class="mb-2 text-3xl font-bold">E2E Probe</h1>
  <p data-testid="probe-greeting" class="mb-6 text-gray-600">{greeting}</p>

  {#if success}
    <p data-testid="probe-flash" class="mb-6 rounded bg-green-500 p-3 text-white">{success}</p>
  {/if}

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">Validation</h2>
    <form onsubmit={submitPrimary}>
      <label for="probe-name" class="mb-1 block text-sm font-medium">Name</label>
      <input id="probe-name" type="text" bind:value={form.name} class="mb-1 w-full rounded border p-2" />
      {#if form.errors.name}
        <p class="mb-2 text-sm text-red-500">{form.errors.name}</p>
      {/if}
      <label for="probe-email" class="mb-1 block text-sm font-medium">Email</label>
      <input id="probe-email" type="text" bind:value={form.email} class="mb-1 w-full rounded border p-2" />
      {#if form.errors.email}
        <p class="mb-2 text-sm text-red-500">{form.errors.email}</p>
      {/if}
      <button type="submit" class="mt-2 rounded bg-indigo-600 px-4 py-2 text-white">Submit probe form</button>
    </form>
  </section>

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">Named error bag</h2>
    <form onsubmit={submitSecondary}>
      <label for="probe-title" class="mb-1 block text-sm font-medium">Title</label>
      <input id="probe-title" type="text" bind:value={secondary.title} class="mb-1 w-full rounded border p-2" />
      <label for="probe-body" class="mb-1 block text-sm font-medium">Body</label>
      <input id="probe-body" type="text" bind:value={secondary.body} class="mb-1 w-full rounded border p-2" />
      <button type="submit" class="mt-2 rounded bg-indigo-600 px-4 py-2 text-white">Submit probe secondary</button>
    </form>
    {#if bagErrors}
      <div data-testid="probe-bag-errors" class="mt-3">
        <h3 class="font-medium">probeSecondary.errors</h3>
        {#each Object.entries(bagErrors) as [key, message]}
          <p class="text-sm text-red-500">{message}</p>
        {/each}
      </div>
    {/if}
  </section>

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">Deferred prop</h2>
    <p data-testid="probe-slow" class="mb-2">{slow ?? 'pending'}</p>
    <button type="button" class="rounded bg-indigo-600 px-4 py-2 text-white" onclick={loadSlow}>
      Load slow prop
    </button>
  </section>

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">Once prop</h2>
    {#if notice}
      <p data-testid="probe-notice" class="mb-2">{notice}</p>
    {/if}
    <button type="button" class="rounded bg-indigo-600 px-4 py-2 text-white" onclick={suppressNotice}>
      Suppress notice
    </button>
  </section>

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">Mergeable entries</h2>
    <p data-testid="probe-entries-count" class="mb-2">{entries.length} entries</p>
    <ul data-testid="probe-entries" class="mb-2">
      {#each entries as entry (entry.id)}
        <li>{entry.id}: {entry.name}</li>
      {/each}
    </ul>
    <button type="button" class="rounded bg-indigo-600 px-4 py-2 text-white" onclick={fetchNextEntry}>
      Fetch next entry
    </button>
  </section>

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">Instant visit</h2>
    <button type="button" class="rounded bg-indigo-600 px-4 py-2 text-white" onclick={visitTarget}>
      Visit target instantly
    </button>
  </section>

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">Redirect back</h2>
    <button type="button" class="rounded bg-indigo-600 px-4 py-2 text-white" onclick={redirectBack}>
      Submit and redirect back
    </button>
  </section>

  <section class="mb-8 rounded bg-white p-6 shadow">
    <h2 class="mb-4 text-xl font-bold">File upload</h2>
    <form onsubmit={submitUpload}>
      <input id="probe-photo" type="file" class="mb-2 block" onchange={onPhoto} />
      {#if upload.errors.photo}
        <p class="mb-2 text-sm text-red-500">{upload.errors.photo}</p>
      {/if}
      <button type="submit" class="rounded bg-indigo-600 px-4 py-2 text-white">Upload photo</button>
    </form>
  </section>
</div>

// examples/spring/spring-pingcrm-react/src/main/webui/resources/js/Pages/Probe/Index.tsx
import { Head, router, useForm, usePage } from '@inertiajs/react'
import type { FormEvent } from 'react'
import type { PageProps } from '@/types'

interface ProbeEntry {
  id: number
  name: string
}

interface ProbePageProps extends PageProps {
  greeting: string
  notice?: string | null
  slow?: string | null
  entries: ProbeEntry[]
}

/**
 * E2E feature probe (Fase E): exercises the full Inertia v3 contract through
 * the official React client on a public route (no login required).
 *
 * The probe is served under a variant base (/e2e-probe on Spring/JAX-RS,
 * /e2e-probe-rx on Reactive Routes): probeBase() derives it from the current
 * URL so every form post and visit targets the same transport
 * (E2E_PROBE_BASE). It is only invoked from event handlers, so server-side
 * rendering never touches window.
 */
function probeBase(): string {
  return window.location.pathname.replace(/\/target\/?$/, '').replace(/\/+$/, '')
}

export default function ProbeIndex() {
  const { props } = usePage<ProbePageProps>()
  const form = useForm({ name: '', email: '' })
  const secondary = useForm({ title: '', body: '' })
  const upload = useForm<{ photo: File | null }>({ photo: null })

  const bagErrors = ((props.errors ?? {}) as Record<string, unknown>)
    .probeSecondary as Record<string, string> | undefined

  const submitPrimary = (e: FormEvent) => {
    e.preventDefault()
    form.post(probeBase() + '/validate')
  }

  const submitSecondary = (e: FormEvent) => {
    e.preventDefault()
    secondary.post(probeBase() + '/validate-secondary', {
      headers: { 'X-Inertia-Error-Bag': 'probeSecondary' },
    })
  }

  const submitUpload = (e: FormEvent) => {
    e.preventDefault()
    upload.post(probeBase() + '/upload')
  }

  return (
    <div className="mx-auto max-w-3xl p-8">
      <Head title="E2E Probe" />
      <h1 className="mb-2 text-3xl font-bold">E2E Probe</h1>
      <p data-testid="probe-greeting" className="mb-6 text-gray-600">
        {props.greeting}
      </p>

      {props.success && (
        <p data-testid="probe-flash" className="mb-6 rounded bg-green-500 p-3 text-white">
          {props.success}
        </p>
      )}

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">Validation</h2>
        <form onSubmit={submitPrimary}>
          <label className="mb-1 block text-sm font-medium" htmlFor="probe-name">
            Name
          </label>
          <input
            id="probe-name"
            type="text"
            className="mb-1 w-full rounded border p-2"
            value={form.data.name}
            onChange={(e) => form.setData('name', e.target.value)}
          />
          {form.errors.name && <p className="mb-2 text-sm text-red-500">{form.errors.name}</p>}
          <label className="mb-1 block text-sm font-medium" htmlFor="probe-email">
            Email
          </label>
          <input
            id="probe-email"
            type="text"
            className="mb-1 w-full rounded border p-2"
            value={form.data.email}
            onChange={(e) => form.setData('email', e.target.value)}
          />
          {form.errors.email && <p className="mb-2 text-sm text-red-500">{form.errors.email}</p>}
          <button type="submit" className="btn-indigo mt-2">
            Submit probe form
          </button>
        </form>
      </section>

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">Named error bag</h2>
        <form onSubmit={submitSecondary}>
          <label className="mb-1 block text-sm font-medium" htmlFor="probe-title">
            Title
          </label>
          <input
            id="probe-title"
            type="text"
            className="mb-1 w-full rounded border p-2"
            value={secondary.data.title}
            onChange={(e) => secondary.setData('title', e.target.value)}
          />
          <label className="mb-1 block text-sm font-medium" htmlFor="probe-body">
            Body
          </label>
          <input
            id="probe-body"
            type="text"
            className="mb-1 w-full rounded border p-2"
            value={secondary.data.body}
            onChange={(e) => secondary.setData('body', e.target.value)}
          />
          <button type="submit" className="btn-indigo mt-2">
            Submit probe secondary
          </button>
        </form>
        {bagErrors && (
          <div data-testid="probe-bag-errors" className="mt-3">
            <h3 className="font-medium">probeSecondary.errors</h3>
            {Object.entries(bagErrors).map(([key, message]) => (
              <p key={key} className="text-sm text-red-500">
                {message}
              </p>
            ))}
          </div>
        )}
      </section>

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">Deferred prop</h2>
        <p data-testid="probe-slow" className="mb-2">
          {props.slow ?? 'pending'}
        </p>
        <button
          type="button"
          className="btn-indigo"
          onClick={() => router.reload({ only: ['slow'] })}
        >
          Load slow prop
        </button>
      </section>

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">Once prop</h2>
        {props.notice && (
          <p data-testid="probe-notice" className="mb-2">
            {props.notice}
          </p>
        )}
        <button
          type="button"
          className="btn-indigo"
          onClick={() =>
            router.reload({ headers: { 'X-Inertia-Except-Once-Props': 'notice' } })
          }
        >
          Suppress notice
        </button>
      </section>

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">Mergeable entries</h2>
        <p data-testid="probe-entries-count" className="mb-2">
          {props.entries.length} entries
        </p>
        <ul data-testid="probe-entries" className="mb-2">
          {props.entries.map((entry) => (
            <li key={entry.id}>
              {entry.id}: {entry.name}
            </li>
          ))}
        </ul>
        <button
          type="button"
          className="btn-indigo"
          onClick={() => router.reload({ only: ['entries'] })}
        >
          Fetch next entry
        </button>
      </section>

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">Instant visit</h2>
        <button
          type="button"
          className="btn-indigo"
          onClick={() =>
            router.visit(probeBase() + '/target?delay=2', {
              component: 'Probe/Target',
              pageProps: (current: Record<string, unknown>, shared: Record<string, unknown>) => ({
                ...shared,
                greeting: `Navigating from probe (was: "${String(current.greeting)}")`,
              }),
            })
          }
        >
          Visit target instantly
        </button>
      </section>

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">Redirect back</h2>
        <button
          type="button"
          className="btn-indigo"
          onClick={() => router.post(probeBase() + '/redirect-back')}
        >
          Submit and redirect back
        </button>
      </section>

      <section className="mb-8 rounded bg-white p-6 shadow">
        <h2 className="mb-4 text-xl font-bold">File upload</h2>
        <form onSubmit={submitUpload}>
          <input
            id="probe-photo"
            type="file"
            className="mb-2 block"
            onChange={(e) => upload.setData('photo', e.target.files?.[0] ?? null)}
          />
          {upload.errors.photo && <p className="mb-2 text-sm text-red-500">{upload.errors.photo}</p>}
          <button type="submit" className="btn-indigo">
            Upload photo
          </button>
        </form>
      </section>
    </div>
  )
}
