// examples/spring/spring-pingcrm-react/src/main/webui/resources/js/Pages/Users/Create.tsx
import { Head, Link, useForm } from '@inertiajs/react'
import type { FormEvent } from 'react'
import Layout from '@/Shared/Layout'
import TextInput from '@/Shared/TextInput'
import SelectInput from '@/Shared/SelectInput'
import FileInput from '@/Shared/FileInput'
import LoadingButton from '@/Shared/LoadingButton'
import { useSyncErrors } from '@/composables/useSyncErrors'

export interface UserForm {
  first_name: string
  last_name: string
  email: string
  password: string
  owner: boolean
  photo: File | null
}

export default function UserCreate() {
  const form = useForm<UserForm>({
    first_name: '',
    last_name: '',
    email: '',
    password: '',
    owner: false,
    photo: null,
  })
  useSyncErrors(form)

  const store = (e: FormEvent) => {
    e.preventDefault()
    form.post('/users')
  }

  return (
    <Layout>
      <Head title="Create User" />
      <h1 className="mb-8 text-3xl font-bold">
        <Link className="text-indigo-400 hover:text-indigo-600" href="/users">
          Users
        </Link>
        <span className="text-indigo-400 font-medium">/</span> Create
      </h1>
      <div className="max-w-3xl bg-white rounded-md shadow overflow-hidden">
        <form onSubmit={store}>
          <div className="flex flex-wrap -mb-8 -mr-6 p-8">
            <TextInput
              value={form.data.first_name}
              onChange={(first_name) => form.setData('first_name', first_name)}
              error={form.errors.first_name}
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="First name"
            />
            <TextInput
              value={form.data.last_name}
              onChange={(last_name) => form.setData('last_name', last_name)}
              error={form.errors.last_name}
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Last name"
            />
            <TextInput
              value={form.data.email}
              onChange={(email) => form.setData('email', email)}
              error={form.errors.email}
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Email"
            />
            <TextInput
              value={form.data.password}
              onChange={(password) => form.setData('password', password)}
              error={form.errors.password}
              className="pb-8 pr-6 w-full lg:w-1/2"
              type="password"
              autoComplete="new-password"
              label="Password"
            />
            <SelectInput
              value={form.data.owner}
              onChange={(value) => form.setData('owner', value === 'true')}
              error={form.errors.owner}
              className="pb-8 pr-6 w-full lg:w-1/2"
              label="Owner"
            >
              <option value="true">Yes</option>
              <option value="false">No</option>
            </SelectInput>
            <FileInput
              value={form.data.photo}
              onChange={(photo) => form.setData('photo', photo)}
              error={form.errors.photo}
              className="pb-8 pr-6 w-full lg:w-1/2"
              accept="image/*"
              label="Photo"
            />
          </div>
          <div className="flex items-center justify-end px-8 py-4 bg-gray-50 border-t border-gray-100">
            <LoadingButton loading={form.processing} className="btn-indigo" type="submit">
              Create User
            </LoadingButton>
          </div>
        </form>
      </div>
    </Layout>
  )
}

// examples/quarkus/pingcrm/src/main/webui/resources/js/Pages/Users/Create.vue
<template>
  <div>
    <Head title="Create User" />
    <h1 class="mb-8 text-3xl font-bold">
      <Link class="text-indigo-400 hover:text-indigo-600" href="/users">Users</Link>
      <span class="text-indigo-400 font-medium">/</span> Create
    </h1>
    <div class="max-w-3xl bg-white rounded-md shadow overflow-hidden">
      <form @submit.prevent="store">
        <div class="flex flex-wrap -mb-8 -mr-6 p-8">
          <text-input v-model="form.first_name" :error="form.errors.first_name" class="pb-8 pr-6 w-full lg:w-1/2" label="First name" />
          <text-input v-model="form.last_name" :error="form.errors.last_name" class="pb-8 pr-6 w-full lg:w-1/2" label="Last name" />
          <text-input v-model="form.email" :error="form.errors.email" class="pb-8 pr-6 w-full lg:w-1/2" label="Email" />
          <text-input v-model="form.password" :error="form.errors.password" class="pb-8 pr-6 w-full lg:w-1/2" type="password" autocomplete="new-password" label="Password" />
          <select-input v-model="form.owner" :error="form.errors.owner" class="pb-8 pr-6 w-full lg:w-1/2" label="Owner">
            <option value="true">Yes</option>
            <option value="false">No</option>
          </select-input>
          <file-input v-model="form.photo" :error="form.errors.photo" class="pb-8 pr-6 w-full lg:w-1/2" type="file" accept="image/*" label="Photo" />
        </div>
        <div class="flex items-center justify-end px-8 py-4 bg-gray-50 border-t border-gray-100">
          <loading-button :loading="form.processing" class="btn-indigo" type="submit">Create User</loading-button>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
import { Head, Link, useForm } from '@inertiajs/vue3'
import Layout from '@/Shared/Layout.vue'
import FileInput from '@/Shared/FileInput.vue'
import TextInput from '@/Shared/TextInput.vue'
import SelectInput from '@/Shared/SelectInput.vue'
import LoadingButton from '@/Shared/LoadingButton.vue'
import { useSyncErrors } from '@/composables/useSyncErrors'

export default {
  components: {
    FileInput,
    Head,
    Link,
    LoadingButton,
    SelectInput,
    TextInput,
  },
  layout: Layout,
  setup() {
    const form = useForm({
      first_name: '',
      last_name: '',
      email: '',
      password: '',
      owner: false,
      photo: null,
    })
    useSyncErrors(form)
    return { form }
  },
  methods: {
    store() {
        this.form.post('/users', {
            forceFormData: true
        })
    },
  },
}
</script>
