// examples/quarkus/quarkus-pingcrm-svelte/src/main/webui/src/lib/Layout.svelte
<script>
  import { router } from '@inertiajs/svelte'
  import FlashMessages from './FlashMessages.svelte'
  import Logo from './Logo.svelte'
  import MainMenu from './MainMenu.svelte'

  let { children } = $props()
  let dropdownOpen = $state(false)
  let mobileOpen = $state(false)

  function toggleDropdown() {
    dropdownOpen = !dropdownOpen
  }

  function toggleMobile() {
    mobileOpen = !mobileOpen
  }

  function logout() {
    router.delete('/logout')
  }
</script>

<div class="min-h-screen bg-gray-100">
  <div class="md:hidden fixed top-0 left-0 right-0 z-50 bg-indigo-900 h-14 flex items-center px-4">
    <button onclick={toggleMobile} class="text-white p-1" aria-label="Menu">
      <svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
      </svg>
    </button>
    <div class="ml-4">
      <Logo />
    </div>
  </div>

  {#if mobileOpen}
    <div class="fixed inset-0 z-40 md:hidden">
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div class="fixed inset-0 bg-black/50" onclick={toggleMobile}></div>
      <div class="fixed inset-y-0 left-0 w-64 bg-indigo-900 z-50 overflow-y-auto">
        <div class="p-4">
          <Logo />
          <div class="mt-4">
            <MainMenu />
          </div>
        </div>
      </div>
    </div>
  {/if}

  <div class="flex">
    <div class="hidden md:block fixed inset-y-0 left-0 w-64 bg-indigo-900 z-30 overflow-y-auto">
      <div class="p-4 pt-6">
        <Logo />
        <div class="mt-8">
          <MainMenu />
        </div>
      </div>
    </div>

    <div class="flex-1 md:ml-64">
      <div class="hidden md:flex h-14 bg-white border-b items-center justify-between px-6">
        <div></div>
        <div class="relative">
          <button
            onclick={toggleDropdown}
            class="flex items-center text-sm text-gray-700 hover:text-gray-900 focus:outline-none"
          >
            <span class="mr-1">John</span>
            <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
            </svg>
          </button>
          {#if dropdownOpen}
            <div class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-50">
              <a href="/contacts" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" onclick={() => { dropdownOpen = false }}>My Contacts</a>
              <hr class="my-1" />
              <button onclick={logout} class="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Logout</button>
            </div>
          {/if}
        </div>
      </div>

      <div class="md:hidden h-14"></div>

      <FlashMessages />

      <div class="p-6">
        {@render children()}
      </div>
    </div>
  </div>
</div>

// examples/quarkus/pingcrm-react/src/main/webui/resources/js/Shared/Layout.tsx
import type { ReactNode } from 'react'
import { Link, usePage } from '@inertiajs/react'
import Dropdown from '@/Shared/Dropdown'
import FlashMessages from '@/Shared/FlashMessages'
import Icon from '@/Shared/Icon'
import Logo from '@/Shared/Logo'
import MainMenu from '@/Shared/MainMenu'
import type { PageProps } from '@/types'

export default function Layout({ children }: { children: ReactNode }) {
  const { auth } = usePage<PageProps>().props

  return (
    <div>
      <div id="dropdown" />
      <div className="md:flex md:flex-col">
        <div className="md:flex md:flex-col md:h-screen">
          <div className="md:flex md:shrink-0">
            <div className="flex items-center justify-between px-6 py-4 bg-indigo-900 md:shrink-0 md:justify-center md:w-56">
              <Link className="mt-1" href="/">
                <Logo className="fill-white" width={120} height={28} />
              </Link>
              <Dropdown
                className="md:hidden"
                placement="bottom-end"
                trigger={
                  <svg className="w-6 h-6 fill-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
                  </svg>
                }
              >
                <div className="mt-2 px-8 py-4 bg-indigo-800 rounded shadow-lg">
                  <MainMenu />
                </div>
              </Dropdown>
            </div>
            <div className="md:text-md flex items-center justify-between p-4 w-full text-sm bg-white border-b md:px-12 md:py-0">
              <div className="mr-4 mt-1">{auth.user?.account.name}</div>
              <Dropdown
                className="mt-1"
                placement="bottom-end"
                trigger={
                  <div className="group flex items-center cursor-pointer select-none">
                    <div className="mr-1 text-gray-700 group-hover:text-indigo-600 focus:text-indigo-600 whitespace-nowrap">
                      <span>{auth.user?.first_name}</span>
                      <span className="hidden md:inline">&nbsp;{auth.user?.last_name}</span>
                    </div>
                    <Icon className="w-5 h-5 fill-gray-700 group-hover:fill-indigo-600 focus:fill-indigo-600" name="cheveron-down" />
                  </div>
                }
              >
                <div className="mt-2 py-2 text-sm bg-white rounded shadow-xl">
                  <Link className="block px-6 py-2 hover:text-white hover:bg-indigo-500" href={`/users/${auth.user?.id}/edit`}>
                    My Profile
                  </Link>
                  <Link className="block px-6 py-2 hover:text-white hover:bg-indigo-500" href="/users">
                    Manage Users
                  </Link>
                  <Link className="block px-6 py-2 w-full text-left hover:text-white hover:bg-indigo-500" href="/logout" method="delete" as="button">
                    Logout
                  </Link>
                </div>
              </Dropdown>
            </div>
          </div>
          <div className="md:flex md:grow md:overflow-hidden">
            <div className="hidden shrink-0 p-12 w-56 bg-indigo-800 overflow-y-auto md:block">
              <MainMenu />
            </div>
            <div className="px-4 py-8 md:flex-1 md:p-12 md:overflow-y-auto">
              <FlashMessages />
              {children}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
